apiVersion: apps/v1
kind: Deployment
metadata:
  name: link
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-ui
  template:
    metadata:
      labels:
        app: link-ui
    spec:
      containers:
        - name: link-ui
          image: link-ui:latest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 400m
              memory: 500Mi
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf