apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-pg
spec:
  selector:
    matchLabels:
      app: link-pg
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: link-pg
    spec:
      containers:
        - image: postgres
          name: link-pg
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DATABASE_USERNAME
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DATABASE_NAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 5432
              hostPort: 5432
              name: tcp-5432
          volumeMounts:
            - name: pg-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-persistent-storage
          persistentVolumeClaim:
            claimName: link-pg-pvc