apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: konfi-pvc
spec:
  accessModes:
# only accessable from one pod:
    - ReadWriteOnce
# accessable from multiple pods:
#    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi