apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: link-pg-pvc
spec:
  accessModes:
    - ReadWriteOnce
# accessable from multiple pods:
#    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi