apiVersion: v1
kind: Service
metadata:
  name: link-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubernetes.io/service-name: "link-postgres"
spec:
  selector:
    app: link-pg
  ports:
    - port: 5432

