apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: link-pg
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    matchLabels:
      app: link-pg
  serviceName: link-pg
  replicas: 1
  template:
    metadata:
      labels:
        app: link-pg
    spec:
      containers:
        - image: postgres
          name: link-pg
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DATABASE_USERNAME
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DATABASE_NAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: DATABASE_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/data
          ports:
            - containerPort: 5432
              hostPort: 5432
              name: tcp-5432
          volumeMounts:
            - name: link-pg-data-dev
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: link-pg-data-dev
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi