apiVersion: v1
kind: Service
metadata:
  name: link-back
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    service.kubernetes.io/service-proxy-name: "link-back"
spec:
  selector:
    app: link-back
  ports:
    - port: 8080

