kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: link-dev
images:
  - name: link-back
    newName: registry.digitalocean.com/denic0la-ocean/link-back
    newTag: v1.0.3
  - name: link-ui
    newName: registry.digitalocean.com/denic0la-ocean/link-ui
    newTag: v0.0.1
  - name: postgres
    newName: registry.digitalocean.com/denic0la-ocean/postgres
    newTag: alpine-15


resources:
  - ../base
  - ingress.yaml
  - sealedsecret_database-config.yaml

configMapGenerator:
  - files:
      - application-prod.yaml
    name: application-config
  - files:
      - nginx.conf
    name: nginx-config


#patches:
#  - path: patch-stop-all.yaml
#    target:
#      kind: Deployment
