
quarkus:

  #  kubernetes:
  #    init-task-defaults:
  #      wait-for-container:
  #        image: "groundnuty/k8s-wait-for:no-root-v1.7"
  log:
    file:
      enabled: false
    socket:
      enabled: false
    console:
      json:
        enabled: true
        pretty-print: true
        print-details: true
    syslog:
      enabled: false

  datasource:
    db-kind: postgresql
    password: ${DATABASE_PASSWORD}
    database: ${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    jdbc:
      url: jdbc:postgresql://link-postgres/${DATABASE_NAME}
      driver: org.postgresql.Driver

  flyway:
    migrate-at-start: true
  http:
    port: 8080

app:
  base-url: https://link.denic0la.ch
